networks:
  mock:

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sleep infinity
    ports:
      - "3333:3333"
    env_file:
      - .env
      # - .env.secret
    volumes:
      - ..:/workspace:cached
    networks:
      - mock
